server:
  port: 8043
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bond?serverTimezone=UTC&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  freemarker:
    cache: false
mybatis-plus:
   mapper-locations: classpath:mapping/*.xml
   typeAliasesPackage: com.dev.bond.entity
   configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
